### ISSUE TITLE
waas_steer with ATU 300

### ISSUE THREAD

**Issue by jaredta2** [torriem/waas_steer#2]
Hi, does anyone here know if using waas_steer allows an AutoTrac Universal 300 unit to function with an iTC receiver? I believe the ATU 300 technically only works with Starfire 3000 and 6000 receivers, but I am not sure if the ATU 300 can detect what model the receiver is. I assume that if it thinks it's using SF1, it should be fine? The display is GreenStar 1800.

**Comment by torriem** [comment]
It should, yes.
